export const content = [
  {
    img: 'https://react-projects-5-menu.netlify.app/images/item-1.jpeg',
    header: 'Buttermilk Pancakes',
    price: '$15',
    category: 'Breakfast',
    desc: 'Im baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed',
    id: 1,
  },
  {
    img: 'https://react-projects-5-menu.netlify.app/images/item-2.jpeg',
    header: 'Diner Double',
    price: '$15',
    category: 'Lunch',
    desc: 'vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats',
    id: 2,
  },
  {
    img: 'https://react-projects-5-menu.netlify.app/images/item-3.jpeg',
    header: 'Godzilla Milkshake',
    price: '$25',
    category: 'Shakes',
    desc: 'ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.',
    id: 3,
  },
  {
    img: 'https://react-projects-5-menu.netlify.app/images/item-4.jpeg',
    header: 'Country Delight',
    price: '$15',
    category: 'Breakfast',
    desc: 'Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut',
    id: 4,
  },
  {
    img: 'https://react-projects-5-menu.netlify.app/images/item-5.jpeg',
    header: 'Egg Attack',
    price: '$10',
    category: 'Lunch',
    desc: "franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up",
    id: 5,
  },
  {
    img: 'https://react-projects-5-menu.netlify.app/images/item-6.jpeg',
    header: 'Oreo Dream',
    price: '$12',
    category: 'Shakes',
    desc: 'Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday',
    id: 6,
  },
  {
    img: 'https://react-projects-5-menu.netlify.app/images/item-7.jpeg',
    header: 'Bacon Overflow',
    price: '$25',
    category: 'Breakfast',
    desc: 'carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird',
    id: 7,
  },
  {
    img: 'https://react-projects-5-menu.netlify.app/images/item-8.jpeg',
    header: 'American Classic',
    price: '$25',
    category: 'Lunch',
    desc: 'on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut',
    id: 8,
  },
];
